config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum:20}
  validates :description, presence: true, length: {minimum: 10}
  validates :author, presence: true, length: {minimum: 3, maximum: 10}
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true, length: {minimum: 3, maximum: 10}
  validates :last_name, presence: true, length:  {minimum: 3, maximum: 10}
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :cellphone, presence: true, numericality: true, :length => { minimum: 8, maximum: 8 }
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: "Article was successfuly created" }
      else
        format.html{render 'articles/new'}
      end
    end
  end

  def index
    @articles = Article.all # PREGUNTAR POR QUÉ ESTA LLEVA S
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_path(@article), notice: "Article was successfully updated"}
      else
        format.html {render 'articles/edit'}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @article.destroy
        format.html { redirect_to articles_path, notice: "Article was successfully deleted"}
      else
        format.html {redirect_to articles_path}
      end
    end
  end

end

private
def article_params
  params.require(:article).permit(:title, :description, :author)
end

def set_article
  @article = Article.find(params[:id])
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "User was successfully created"}
      else
        format.html { render 'users/new' }
      end
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html{ redirect_to user_path(@user), notice: "User was successfully updated" }
      else
        format.html{ render 'users/edit'}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.html{ redirect_to users_path, notice: "User was successfully deleted" }
      else
        format.html{ redirect_to users_path}
      end
    end

  end

end

private
def user_params
  params.require(:user).permit(:first_name, :last_name, :email, :cellphone)
end

def set_user
  @user = User.find(params[:id])

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_formulario.html.erb
<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Failed! Este error no permite que se guarden los datos: </strong> <%= msg %>
    </div>
  <%end %>
<% end %>
<div class="container">
  <%= form_for @article do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, type:"text", class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <div class="col text-center">
      <%= f.submit :Submit, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render 'formulario' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do|article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.author %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/articles/new.html.erb
<h1>Create an Article</h1>
<%= render 'formulario' %>

app/views/articles/show.html.erb
<div class="container">
<h1>Showing Selected Articles</h1>
<p>
  Title: <%= @article.title %>
</p>
<p>
  Description: <%= @article.description %>
</p>
<p>
  Author: <%= @article.author %>
</p>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Home
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="<%= articles_path %>">Article</a>
        <a class="dropdown-item" href="<%= users_path %>">User</a>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Create New
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="<%= new_article_path %>">Article</a>
        <a class="dropdown-item" href="<%= new_user_path %>">User</a>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailStore1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/_formulario.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Failed! Este error no permite que se guarden los datos: </strong> <%= msg %>
    </div>
  <%end %>
<% end %>
<div class="container">
  <%= form_for @user do |g| %>
    <div class="form-group">
      <%= g.label :first_name %>
      <%= g.text_field :first_name, type:"text", class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= g.label :last_name %>
      <%= g.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= g.label :email %>
      <%= g.text_area :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= g.label :cellphone %>
      <%= g.text_field :cellphone, class: "form-control" %>
    </div>
    <div class="col text-center">
      <%= g.submit :Submit, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%=render 'users/formulario' %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>CellPhone</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do|user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.cellphone %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<h1>Create new User</h1>
<%= render 'users/formulario' %>

app/views/users/show.html.erb
<div class="container">
  <h1>Showing Selected User</h1>
  <p>
    First Name: <%= @user.first_name %>
  </p>
  <p>
    Last Name: <%= @user.last_name %>
  </p>
  <p>
    Email: <%= @user.email %>
  </p>
  <p>
    CellPhone: <%= @user.cellphone %>
  </p>

</div>